
default: &default
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: sqlite3

test:
  <<: *default
  adapter: sqlite3

production:
  adapter: postgres
  username: myapp
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>